# Generated by Django 2.1.7 on 2019-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=150)),
                ('client_siret', models.CharField(max_length=30)),
                ('client_adresse', models.CharField(max_length=255)),
                ('client_cp', models.CharField(max_length=20)),
                ('client_ville', models.CharField(max_length=60)),
            ],
        ),
    ]
