# Generated by Django 2.1.7 on 2019-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('societe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=60)),
                ('pathlogo', models.TextField()),
                ('pseudo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
